const ar = 

{
    "Home": "الرئيسية",
    "Care": "العناية",
    "Planning": "التخطيط",
    "Profile": "الملف الشخصي",
    "Hello": "مرحبًا",
    "Check_your_plants_today": "تحقق من نباتاتك اليوم",
    "See_what's_new": "انظر ما هو جديد",
    "Concerns_Tunisia_overall": "قلق عام تونس",
    "Get_Premium": "احصل على مميزات إضافية",
    "Get_new_features": "احصل على مميزات جديدة",
    "Management": "الإدارة",
    "Veterinarian": "طبيب بيطري",
    "Chat": "المحادثة",
    "Health-care": "رعاية الصحة",
    "Price": "السعر",
    "Pay_now": "ادفع الآن",
    "See_your_stock": "انظر مخزونك",
    "Manage_your_farm": "أدر مزرعتك",
    "Check_your_plants": "تحقق من نباتاتك",
    "This_is_what_you_have": "هذا ما تمتلكه",
    "Cows": "الأبقار",
    "Sheep": "الأغنام",
    "Olive_Trees": "أشجار الزيتون",
    "Quantity": "الكمية",
    "Select_an_animal": "اختر حيوانًا",
    "Select_Sexe": "اختر الجنس",
    "Age": "العمر",
    "Weight": "الوزن",
    "Birthday": "تاريخ الميلاد",
    "Male": "ذكر",
    "Female": "أنثى",
    "Switch_to_Tree": "التحول إلى الأشجار",
    "Submit": "إرسال",
    "Price_Buying": "سعر الشراء",
    "Select_a_tree": "اختر شجرة",
    "Select_Image": "اختر صورة",
    "Allow_Expo_Go_to_access_photos_and_videos_on_this_device": "السماح لـ Expo Go بالوصول إلى الصور ومقاطع الفيديو على هذا الجهاز",
    "Select_photos_and_videos": "اختر الصور ومقاطع الفيديو",
    "Allow_all": "السماح بالكل",
    "Don't_allow": "عدم السماح",
    "Select_photos_and_videos_you_allow_this_app_to_access": "اختر الصور ومقاطع الفيديو التي تسمح لهذا التطبيق بالوصول إليها",
    "Photos": "الصور",
    "Albums": "الألبومات",
    "Recent": "الأحدث",
    "Alert": "تنبيه",
    "Permission_to_access_the_media_library_is_required": "الإذن للوصول إلى مكتبة الوسائط مطلوب",
    "OK": "موافق",
    "This_app_can_only_access_the_photos_you_select": "يمكن لهذا التطبيق الوصول فقط إلى الصور التي تختارها",
    "Browse": "تصفح",
    "Downloads": "التنزيلات",
    "Large_files": "الملفات الكبيرة",
    "This_week": "هذا الأسبوع",
    "Images_in_Downloads": "الصور في التنزيلات",
    "Images": "الصور",
    "Sort_by": "فرز حسب",
    "Don't_show_hidden_files": "عدم عرض الملفات المخفية",
    "SDCARD": "بطاقة الذاكرة",
    "Drive": "التخزين",
    "Media": "وسائط",
    "Photos": "الصور",
    "Open_form": "فتح النموذج",
    "Keep_in_mind": "تذكير",
    "Daily_forecast": "التنبؤ اليومي",
    "Patchy_rain_possible": "ممكن تساقط الأمطار",
    "km": "كم",
    "AM": "ص",
    "PM": "م",
    "Monday": "الاثنين",
    "Tuesday": "الثلاثاء",
    "Wednesday": "الأربعاء",
    "Thursday": "الخميس",
    "Friday": "الجمعة",
    "Saturday": "السبت",
    "Sunday": "الأحد",
    "Search_city": "بحث عن مدينة",
    "Colomadu, Indonesia": "كولومادو، إندونيسيا",
    "January": "يناير",
    "February": "فبراير",
    "March": "مارس",
    "April": "إبريل",
    "May": "مايو",
    "June": "يونيو",
    "July": "يوليو",
    "August": "أغسطس",
    "September": "سبتمبر",
    "October": "أكتوبر",
    "November": "نوفمبر",
    "December": "ديسمبر",
    "Partly_cloudy": "جزئيا غائم",
    "Wallet": "المحفظة",
    "LOGOUT": "تسجيل الخروج",
    "Published_At": "نشر في",
    "Select_a_User_to_Start_a_Conversation": "اختر مستخدمًا لبدء محادثة",
    "Search": "بحث",
    "Example_Disease": "مثال على مرض",
    "Onboarding": "توجيه",
    "Done_with_React_Native_Onboarding_Swiper": "تم الانتهاء من دليل التثبيت باستخدام React Native Onboarding Swiper",
    "Skip": "تخطي",
    "Next": "التالي",
    "Second_Page": "الصفحة الثانية",
    "This_is_the_second_page_with_a_different_video": "هذه هي الصفحة الثانية مع فيديو مختلف",
    "Login": "تسجيل الدخول",
    "Email": "البريد الإلكتروني",
    "Password": "كلمة المرور",
    "Don't_have_an_account": "ليس لديك حساب؟",
    "Sign_Up": "سجل الآن",
    "Full_Name": "الاسم الكامل",
    "Address": "العنوان",
    "Phone_Number": "رقم الهاتف",
    "Budget": "الميزانية",
    "Choose_a_picture_or_Take_one": "اختر صورة أو التقط واحدة",
    "Choose_from_Device": "اختر من الجهاز",
    "Open_Camera": "افتح الكاميرا",
    "Already_have_an_account": "لديك حساب بالفعل؟",
    "Oops_Transfer_Failed": "عذرًا، فشلت عملية التحويل",
    "Date": "التاريخ",
    "Time": "الوقت",
    "Status": "الحالة",
    "Pending": "قيد الانتظار",
    "Reference_No": "الرقم المرجعي",
    "We_can't_send_the_money_to_the_user_please_don't_close_the_app_while_transaction_happens": "لا يمكننا إرسال المال إلى المستخدم. من فضلك، لا تقم بإغلاق التطبيق أثناء عملية التحويل.",
    "Try_Again": "حاول مرة أخرى",
    "Transfer_Successfully_Done": "تمت عملية التحويل بنجاح",
    "Success": "نجاح",
    "Save_Receipt": "احفظ الإيصال",
    "":"",
    "":"",
    "":"",
    "":""
  }
  

export default  ar 